name: Animalium Test

on: push

jobs:
 test:
   name: run test
   runs-on:  ubuntu-20.04
   services:
     postgres:
       image: postgres:12
       env:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: animalium_test
       ports:
       - 5432:5432
       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
   env:
     MIX_ENV: test
   steps:
     - uses: actions/checkout@v2
     - uses: erlef/setup-beam@v1
       with:
         otp-version: "24"
         elixir-version: "1.13.1"
         rebar3-version: "3.15"
     - uses: actions/cache@v2
       with:
         path: deps
         key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
         restore-keys: |
           ${{ runner.os }}-mix-
     - uses: actions/setup-node@v1
       with:
         node-version: '10.x'
     - uses: nanasess/setup-chromedriver@master
       with:
         chromedriver-version: '79.0.3945.36'
     - run: |
         export DISPLAY=:99
         chromedriver --url-base=/wd/hub &
         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
         
     - name: Install dependencies
       run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        npm install --prefix assets
        npm run deploy --prefix assets
        
     - name: Run test
       run: mix test